# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "82a2711c8f4624ecbd741b6cc8aca69d"
application_url = "https://index-telescope-frequency-albums.trycloudflare.com"
embedded = true
name = "shipping-calculator"
handle = "shipping-calculator-31"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://index-telescope-frequency-albums.trycloudflare.com/auth/callback",
  "https://index-telescope-frequency-albums.trycloudflare.com/auth/shopify/callback",
  "https://index-telescope-frequency-albums.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "dmohit.myshopify.com"
automatically_update_urls_on_dev = true
# This file stores configurations for your Shopify app.

scopes = "write_products, write_delivery_customizations"